version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "freelance-backend"
s3_prefix = "freelance-backend"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
s3_bucket = "freelance-backend-bucket"
parameter-overrides = "ParameterName=\"parameterValue\""
resolve_s3 = true
parameter_overrides = "CallbackUrl=\"https://example.com/callback\""
