AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Freelance Job/Task Platform
  Serverless freelance platform base template for team development.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  FreelancePlatformApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${Environment}-freelance-platform-api"
      Description: Freelance Platform REST API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Nested stack for Auth Service
  AuthServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./auth-service/template.yaml
      Parameters:
        Environment: !Ref Environment

Outputs:
  FreelancePlatformApiId:
    Description: "API Gateway REST API ID"
    Value: !Ref FreelancePlatformApi
    Export:
      Name: !Sub "${Environment}-freelance-api-id"

  FreelancePlatformApiRootResourceId:
    Description: "API Gateway Root Resource ID"
    Value: !GetAtt FreelancePlatformApi.RootResourceId
    Export:
      Name: !Sub "${Environment}-freelance-api-root-id"

  AuthUserPoolId:
    Description: "Cognito User Pool Id from Auth Service"
    Value: !GetAtt AuthServiceStack.Outputs.UserPoolId
    Export:
      Name: !Sub "${Environment}-auth-user-pool-id"

  AuthUserPoolClientId:
    Description: "Cognito User Pool Client Id from Auth Service"
    Value: !GetAtt AuthServiceStack.Outputs.UserPoolClientId
    Export:
      Name: !Sub "${Environment}-auth-user-pool-client-id"