AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Freelance Job/Task Platform
 
  Serverless freelance platform base template for team development.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  FreelancePlatformApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${Environment}-freelance-platform-api"
      Description: Freelance Platform REST API
      EndpointConfiguration:
        Types:
          - REGIONAL

Outputs:
  FreelancePlatformApiId:
    Description: "API Gateway REST API ID"
    Value: !Ref FreelancePlatformApi
    Export:
      Name: !Sub "${Environment}-freelance-api-id"
